### ISSUE TITLE
Cannot set property 'role' of undefined on login

### ISSUE THREAD

**Issue by jackusm** [Raffy27/OrionServer#3]
Started getting this error even with a fresh download
```
INFO Listening started.
INFO Loaded 0 bot(s).
INFO Loaded 0 blacklist entries.
INFO Loaded 1 user(s).
login admin admin
readline.js:1086
            throw err;
            ^

TypeError: Cannot set property 'role' of undefined
    at Object.exports.login (D:\snapshot\OrionServer\database.js:109:18)
    at Interface.<anonymous> (D:\snapshot\OrionServer\app.js:92:28)
    at Interface.emit (events.js:198:13)
    at Interface._onLine (readline.js:308:10)
    at Interface._line (readline.js:656:8)
    at Interface._ttyWrite (readline.js:937:14)
    at ReadStream.onkeypress (readline.js:184:10)
    at ReadStream.emit (events.js:198:13)
    at emitKeys (internal/readline.js:424:14)
    at emitKeys.next (<anonymous>)
```

**Comment by Raffy27** [comment]
You are right, this is a bug introduced by the last login mechanism. I forgot to update the command version accordingly. Although I didn't plan on maintaining this project for any longer, I'll fix this simply because it looks bad.

**Comment by Raffy27** [comment]
Should be fixed, thanks for the heads up!
