### ISSUE TITLE
help with the miner

### ISSUE THREAD

**Issue by GigaZero** [Raffy27/OrionServer#4]
hey i did what did you say with the miner 

**The cryptocurrency mining module depends on Nanominer. Get the release archive from the original repository and save it as Server\files\miner.zip.**

and then i do start mine and in the pool stats noting moved

**Comment by GigaZero** [comment]
and now i have that error in the server console 

TypeError: Cannot read property '1' of undefined
    at D:\snapshot\OrionServer\bots.js:71:40
    at Layer.handle [as handle_request] (D:\snapshot\OrionServer\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\snapshot\OrionServer\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\snapshot\OrionServer\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\snapshot\OrionServer\node_modules\express\lib\router\layer.js:95:5)
    at D:\snapshot\OrionServer\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (D:\snapshot\OrionServer\node_modules\express\lib\router\index.js:335:12)
    at next (D:\snapshot\OrionServer\node_modules\express\lib\router\index.js:275:10)
    at Immediate._onImmediate (D:\snapshot\OrionServer\node_modules\express-session\index.js:502:7)
    at processImmediate (internal/timers.js:458:21)

**Comment by Raffy27** [comment]
Second problem should be fixed as of 35c145be34086d3d53f3841f195dc7f58e015237 (see bots.js), it was probably due to information gathering failing on your system.

As for the miner, please mind the structure of the necessary archive as described in the [**Required structure**](https://github.com/Raffy27/OrionServer/blob/master/SetupGuide.md#additional-modules) spoiler section of the Setup Guide. Make sure that the executable and the configuration file are in the root of the archive. Furthermore, please see whether the miner is active (as a normal process) on your system after issuing the command. Most pools don't offer immediate statistics, so it might take some time for them to refresh your stats.
